#! /usr/bin/env ruby

require 'builder'

def dir_blacklist
  ["css", "sass", "script"]
end

def useless?(f)
  f.start_with?("_") ||
    f.start_with?(".") ||
    !File.directory?(f) ||
    dir_blacklist.include?(f)
end

def get_gif_dirs
  Dir.foreach(".").map { |f| f unless useless?(f) }.compact
end

list = Builder::XmlMarkup.new(
  target: File.open("_includes/site-index.html", 'w'),
  indent: 0,
  margin: 0
)

dirs = get_gif_dirs

list.ul do |builder|
  dirs.each do |dir|
    builder.li do |dir_element|
      dir_element.text!(dir)
      dir_element.ul do |ul|
        Dir.glob("#{dir}/*.gif") do |gif|
          ul.li do |li|
            li.a(
              File.basename(gif),
              "href"  => gif,
              "title" => gif,
              "class" => "gif"
            )
          end
        end
      end
    end
  end
end
